name: "AlignCloud DevBot"
description: "Autonomous agent that edits files, runs shell commands and opens PRs"
author: "AlignCloud"
inputs:
  plan:
    description: "High-level instruction for the bot (JSON or plain text)"
    required: true
  gh_token:
    description: "GitHub token with repo/workflow scope"
    required: true
  openai_key:
    description: "OpenAI API key"
    required: true
runs:
  using: "node20"
  main: "index.js"
